package constant

const (
	C1337xBaseURL            = "https://www.1337x.to"
	FreeGOGListURL           = "https://freegogpcgames.com/a-z-games-list"
	GOGGamesBaseURL          = "https://www.gog-games.to"
	GOGGamesURL              = "https://www.gog-games.to/search/all/%v/date/desc/any"
	GOGSearchURL             = "https://embed.gog.com/games/ajax/filtered"
	GOGDetailsURL            = "https://api.gog.com/products"
	SteamSearchURL           = "https://store.steampowered.com/search"
	SteamAppDetailURL        = "https://store.steampowered.com/api/appdetails"
	SteamAllAppsURL          = "https://api.steampowered.com/ISteamApps/GetAppList/v2/?format=json"
	XatabBaseURL             = "https://byxatab.com"
	GoogleSearchURL          = "https://www.google.com/search"
	BingSearchURL            = "https://www.bing.com/search"
	OnlineFixURL             = "https://online-fix.me"
	OnlineFixCSRFURL         = "https://online-fix.me/engine/ajax/authtoken.php"
	IGDBGameURL              = "https://api.igdb.com/v4/games"
	IGDBSearchURL            = "https://api.igdb.com/v4/search"
	IGDBCompaniesURL         = "https://api.igdb.com/v4/companies"
	IGDBWebsitesURL          = "https://api.igdb.com/v4/websites"
	TwitchAuthURL            = "https://id.twitch.tv/oauth2/token"
	Steam250Top250URL        = "https://steam250.com/top250"
	Steam250BestOfTheYearURL = "https://steam250.com/%v"
	Steam250WeekTop50URL     = "https://steam250.com/7day"
	Steam250MostPlayedURL    = "https://steam250.com/most_played"
	FitGirlURL               = "https://fitgirl-repacks.site/page/%v/"
	SteamRIPBaseURL          = "https://steamrip.com"
	SteamRIPGameListURL      = "https://steamrip.com/games-list-page/"
	RepackInfoURL            = "https://repack.info/page/%v/"
	GnarlyURL                = "https://rentry.org/gnarly_repacks"
)
